server:
  port: 8080

spring:
  profiles: docker
  #  kafka:
  #    producer:
  #    bootstrap-servers: kafka_0:29092,kafka_0:29092
  #    key-serializer: org.apache.kafka.common.serialization.LongSerializer
  #    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  #  application.name: producer-api
  cloud:
    stream:
      kafka.binder:
        brokers:
          - kafka_0:29092,kafka_0:29092